apiVersion: apps/v1
kind: Deployment
metadata:   
    name: danizh-dotnet-deployment
    annotations: 
        kubernetes.io/change-cause: "Updating docker Images to v2"
spec: 
    replicas: 1
    selector:
        matchLabels:
            app: danizh-dotnetapp
    template: 
        metadata:
            name: mydotnetappk8s
            labels:
                env: prod
                app: danizh-dotnetapp
                app.kubernetes.io/name: danizh-dotnetapp
        spec:
            containers:
                - name: danizh-dotnetapp
                  image: danizh/dockerlearning:v1
                  ports:
                     - containerPort: 80
                       name: http-web-api
                  resources:
                     requests:
                         cpu: 100m
                         memory: 100Mi
                     limits:
                         cpu: 200m
                         memory: 200Mi
                  env:
                     - name: ASPNETCORE_URLS
                       value: http://+:80

---

apiVersion: v1
kind: Service
metadata:
    name: my-lb-service   
spec: 
    selector:    
        app.kubernetes.io/name: danizh-dotnetapp
    ports: 
      - name: danizh-dotnet-port
        protocol: TCP
        port: 8080
        targetPort: 80
    type: LoadBalancer
    loadBalancerIP: 192.168.1.7
